name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
 - packages/hetu_script
 - packages/hetu_script_dev_tools

dependencies:
  benchmark_harness: ^2.3.1
  hetu_script:
    path: packages/hetu_script
  hetu_script_dev_tools:
    path: packages/hetu_script_dev_tools

dev_dependencies:
  lints: ^5.1.0
  test: ^1.26.0
  analyzer: ^7.7.0
