name: hetu_script_flutter
description: Extension for Hetu Script. Makes it easier to use Hetu Script in Flutter apps.
version: 0.1.0+2
homepage: https://github.com/hetu-script/hetu-script
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.0
  # hetu_script: '^0.4.2+1'
  hetu_xx:
    path: ../hetu_xx

dev_dependencies:
  lints: ^5.1.0
  test: ^1.26.0
  analyzer: ^7.7.0
